YunchengLiu/my-vcpkg-binarycaches@main:
  - source: hxtplib/vcpkg.json
    dest: vcpkg.json
  - source: hxtplib/vcpkg-configuration.json
    dest: vcpkg-configuration.json
  - source: hxtplib/config/overlay-vcpkg-triplets/hxtp-x64-win.cmake
    dest: config/overlay-vcpkg-triplets/hxtp-x64-win.cmake
