YunchengLiu/my-vcpkg-binarycaches@main:
  - source: fika/vcpkg.json
    dest: vcpkg.json
  - source: fika/vcpkg-configuration.json
    dest: vcpkg-configuration.json
  - source: fika/config/overlay-vcpkg-triplets/fika-x64-win.cmake
    dest: config/overlay-vcpkg-triplets/fika-x64-win.cmake
