name: Sync vcpkg Config Files from hxtplib

on:
  schedule:
    - cron: '0 16 * * *' 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  file-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        # checkout the current repository to github workspace
        # not the current_repo
        uses: actions/checkout@v4

      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          repository: YunchengLiu/hxtplib
          token: ${{ secrets.SYNC_FROM_HXTP_TOKEN }}
          path: hxtplib
          fetch-depth: 0
          persist-credentials: false

      - name: Sync files via repo-file-sync-action
        uses: Redocly/repo-file-sync-action@main
        with:
          GH_PAT: ${{ secrets.VCPKG_CONFIG_FILES_SYNC_WRITE_TOKEN }}
          SKIP_PR: true
          OVERWRITE_EXISTING_PR: true
          COMMIT_EACH_FILE: false
          COMMIT_PREFIX: '[action] 🔄'
          COMMIT_BODY: 'Update vcpkg configs from hxtplib repo'
          GIT_USERNAME: 'github-actions[bot]'
          GIT_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Resolve vcpkg-configuration.json file
        run: |
          cp hxtplib/vcpkg-configuration.json .
          jq '.["overlay-triplets"] = ["overlay-triplets/"]' \
            vcpkg-configuration.json > tmp.json
          mv tmp.json vcpkg-configuration.json

      - name: Commit resolved vcpkg-configuration.json file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[action] 🔧 resolve overlay-triplets path in vcpkg-configuration.json'
          file_pattern: 'vcpkg-configuration.json'